spring.application.name=gateway
server.port=8080

# Eureka

eureka.client.enabled=false

# Rutas
spring.cloud.gateway.routes[0].id=usuarios
spring.cloud.gateway.routes[0].uri=https://ms-usuarios-n9lf.onrender.com
spring.cloud.gateway.routes[0].predicates[0]=Path=/gym/socios/**

spring.cloud.gateway.routes[1].id=auth
spring.cloud.gateway.routes[1].uri=https://ms-usuarios-n9lf.onrender.com
spring.cloud.gateway.routes[1].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[2].id=reservas
spring.cloud.gateway.routes[2].uri=https://reservas-brps.onrender.com
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/Reservas/**

spring.cloud.gateway.routes[3].id=clases
spring.cloud.gateway.routes[3].uri=https://clases-a178.onrender.com
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/clases/**

spring.cloud.gateway.routes[4].id=membresias
spring.cloud.gateway.routes[4].uri=https://membresia.onrender.com
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/membresias/**

spring.cloud.gateway.routes[5].id=planes
spring.cloud.gateway.routes[5].uri=https://plannutricional.onrender.com
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/Planes/**

spring.cloud.gateway.routes[6].id=tienda
spring.cloud.gateway.routes[6].uri=https://ms-tienda-2l75.onrender.com
spring.cloud.gateway.routes[6].predicates[0]=Path=/gym/tienda/**

spring.cloud.gateway.routes[7].id=pagos
spring.cloud.gateway.routes[7].uri=https://ms-pagos-tdr0.onrender.com
spring.cloud.gateway.routes[7].predicates[0]=Path=/gym/pagos/**

spring.cloud.gateway.routes[8].id=entrenadores
spring.cloud.gateway.routes[8].uri=https://ms-entrenadores.onrender.com
spring.cloud.gateway.routes[8].predicates[0]=Path=/gym/entrenadores/**

spring.cloud.gateway.routes[9].id=rutinas
spring.cloud.gateway.routes[9].uri=https://ms-rutinas.onrender.com
spring.cloud.gateway.routes[9].predicates[0]=Path=/gym/rutinas/**

spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}

springdoc.swagger-ui.urls[0].name=usuarios
springdoc.swagger-ui.urls[0].url=https://ms-usuarios-n9lf.onrender.com/v3/api-docs

springdoc.swagger-ui.urls[1].name=reservas
springdoc.swagger-ui.urls[1].url=https://reservas-brps.onrender.com/v3/api-docs

springdoc.swagger-ui.urls[2].name=clases
springdoc.swagger-ui.urls[2].url=https://clases-a178.onrender.com/v3/api-docs

springdoc.swagger-ui.urls[3].name=membresias
springdoc.swagger-ui.urls[3].url=https://membresia.onrender.com/v3/api-docs

springdoc.swagger-ui.urls[4].name=planes
springdoc.swagger-ui.urls[4].url=https://plannutricional.onrender.com/v3/api-docs

springdoc.swagger-ui.urls[5].name=tienda
springdoc.swagger-ui.urls[5].url=https://ms-tienda-2l75.onrender.com/v3/api-docs

springdoc.swagger-ui.urls[6].name=pagos
springdoc.swagger-ui.urls[6].url=https://ms-pagos-tdr0.onrender.com/v3/api-docs

springdoc.swagger-ui.urls[7].name=entrenadores
springdoc.swagger-ui.urls[7].url=https://ms-entrenadores.onrender.com/v3/api-docs

springdoc.swagger-ui.urls[8].name=rutinas
springdoc.swagger-ui.urls[8].url=https://ms-rutinas.onrender.com/v3/api-docs
