spring.application.name=gateway
server.port=8080

# Eureka

eureka.client.enabled=false

# Rutas
spring.cloud.gateway.routes[0].id=usuarios
spring.cloud.gateway.routes[0].uri=https://ms-usuarios-n9lf.onrender.com
spring.cloud.gateway.routes[0].predicates[0]=Path=/gym/socios/**

spring.cloud.gateway.routes[1].id=auth
spring.cloud.gateway.routes[1].uri=https://ms-usuarios-n9lf.onrender.com
spring.cloud.gateway.routes[1].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[2].id=reservas
spring.cloud.gateway.routes[2].uri=https://reservas-brps.onrender.com
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/Reservas/**

spring.cloud.gateway.routes[3].id=clases
spring.cloud.gateway.routes[3].uri=https://clases-a178.onrender.com
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/clases/**

spring.cloud.gateway.routes[4].id=membresias
spring.cloud.gateway.routes[4].uri=https://membresia.onrender.com
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/membresias/**

spring.cloud.gateway.routes[5].id=planes
spring.cloud.gateway.routes[5].uri=https://plannutricional.onrender.com
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/Planes/**

spring.cloud.gateway.routes[6].id=tienda
spring.cloud.gateway.routes[6].uri=https://ms-tienda-2l75.onrender.com
spring.cloud.gateway.routes[6].predicates[0]=Path=/gym/tienda/**

spring.cloud.gateway.routes[7].id=pagos
spring.cloud.gateway.routes[7].uri=https://ms-pagos-tdr0.onrender.com
spring.cloud.gateway.routes[7].predicates[0]=Path=/gym/pagos/**

spring.cloud.gateway.routes[8].id=entrenadores
spring.cloud.gateway.routes[8].uri=https://ms-entrenadores.onrender.com
spring.cloud.gateway.routes[8].predicates[0]=Path=/gym/entrenadores/**

spring.cloud.gateway.routes[9].id=rutinas
spring.cloud.gateway.routes[9].uri=https://ms-rutinas.onrender.com
spring.cloud.gateway.routes[9].predicates[0]=Path=/gym/rutinas/**

spring.cloud.gateway.routes[10].id=usuarios-docs
spring.cloud.gateway.routes[10].uri=https://ms-usuarios-n9lf.onrender.com
spring.cloud.gateway.routes[10].predicates[0]=Path=/usuarios/v3/api-docs
spring.cloud.gateway.routes[10].filters[0]=RewritePath=/usuarios/v3/api-docs, /v3/api-docs

spring.cloud.gateway.routes[11].id=reservas-docs
spring.cloud.gateway.routes[11].uri=https://reservas-brps.onrender.com
spring.cloud.gateway.routes[11].predicates[0]=Path=/reservas/v3/api-docs
spring.cloud.gateway.routes[11].filters[0]=RewritePath=/reservas/v3/api-docs, /v3/api-docs

spring.cloud.gateway.routes[12].id=clases-docs
spring.cloud.gateway.routes[12].uri=https://clases-a178.onrender.com
spring.cloud.gateway.routes[12].predicates[0]=Path=/clases/v3/api-docs
spring.cloud.gateway.routes[12].filters[0]=RewritePath=/clases/v3/api-docs, /v3/api-docs

spring.cloud.gateway.routes[13].id=membresias-docs
spring.cloud.gateway.routes[13].uri=https://membresia.onrender.com
spring.cloud.gateway.routes[13].predicates[0]=Path=/membresias/v3/api-docs
spring.cloud.gateway.routes[13].filters[0]=RewritePath=/membresias/v3/api-docs, /v3/api-docs

spring.cloud.gateway.routes[14].id=planes-docs
spring.cloud.gateway.routes[14].uri=https://plannutricional.onrender.com
spring.cloud.gateway.routes[14].predicates[0]=Path=/planes/v3/api-docs
spring.cloud.gateway.routes[14].filters[0]=RewritePath=/planes/v3/api-docs, /v3/api-docs

spring.cloud.gateway.routes[15].id=tienda-docs
spring.cloud.gateway.routes[15].uri=https://ms-tienda-2l75.onrender.com
spring.cloud.gateway.routes[15].predicates[0]=Path=/tienda/v3/api-docs
spring.cloud.gateway.routes[15].filters[0]=RewritePath=/tienda/v3/api-docs, /v3/api-docs

spring.cloud.gateway.routes[16].id=pagos-docs
spring.cloud.gateway.routes[16].uri=https://ms-pagos-tdr0.onrender.com
spring.cloud.gateway.routes[16].predicates[0]=Path=/pagos/v3/api-docs
spring.cloud.gateway.routes[16].filters[0]=RewritePath=/pagos/v3/api-docs, /v3/api-docs

spring.cloud.gateway.routes[17].id=entrenadores-docs
spring.cloud.gateway.routes[17].uri=https://ms-entrenadores.onrender.com
spring.cloud.gateway.routes[17].predicates[0]=Path=/entrenadores/v3/api-docs
spring.cloud.gateway.routes[17].filters[0]=RewritePath=/entrenadores/v3/api-docs, /v3/api-docs

spring.cloud.gateway.routes[18].id=rutinas-docs
spring.cloud.gateway.routes[18].uri=https://ms-rutinas.onrender.com
spring.cloud.gateway.routes[18].predicates[0]=Path=/rutinas/v3/api-docs
spring.cloud.gateway.routes[18].filters[0]=RewritePath=/rutinas/v3/api-docs, /v3/api-docs

spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}

springdoc.swagger-ui.urls[0].name=usuarios
springdoc.swagger-ui.urls[0].url=/usuarios/v3/api-docs

springdoc.swagger-ui.urls[1].name=reservas
springdoc.swagger-ui.urls[1].url=/reservas/v3/api-docs

springdoc.swagger-ui.urls[2].name=clases
springdoc.swagger-ui.urls[2].url=/clases/v3/api-docs

springdoc.swagger-ui.urls[3].name=membresias
springdoc.swagger-ui.urls[3].url=/membresias/v3/api-docs

springdoc.swagger-ui.urls[4].name=planes
springdoc.swagger-ui.urls[4].url=/planes/v3/api-docs

springdoc.swagger-ui.urls[5].name=tienda
springdoc.swagger-ui.urls[5].url=/tienda/v3/api-docs

springdoc.swagger-ui.urls[6].name=pagos
springdoc.swagger-ui.urls[6].url=/pagos/v3/api-docs

springdoc.swagger-ui.urls[7].name=entrenadores
springdoc.swagger-ui.urls[7].url=/entrenadores/v3/api-docs

springdoc.swagger-ui.urls[8].name=rutinas
springdoc.swagger-ui.urls[8].url=/rutinas/v3/api-docs

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
